version: '3.3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=Jonathan
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432

    volumes:
    - ./postgres_data/data:/var/lib/postgresql/data
